### ISSUE TITLE
Icons on either vuhdo or ElvUI frame.

### ISSUE THREAD

**Issue by joro96** [Tercioo/Open-Raid-Library#41]
Hi! 
Amazing weakaura! 
I'm currently setting up a vuhdo profile for my main buff targets and the weakaura is just what i needed to complete it. 
But if i for example have 2 Dev Evokers and i only have one of them in my vuhdo frame to buff 1 him, DR from the other Evoker will be displayed on my ElvUI Raidframe instead. Is there any way to only display stuff on the Vuhdo frame? 
Thanks alot for the help!

**Comment by Tercioo** [comment]
which weakaura are you referring to?

**Comment by joro96** [comment]
https://wago.io/LibOpenRaidCooldowns
This one.
It works perfectly, but i only want the icons to show on my vuhdo frame, not on the ElvUI frame :/

**Comment by Tercioo** [comment]
You miss understood: this is the github support for the library, not for the weakauras.
For the weakauras, you post on the link you gave to me.

**Comment by joro96** [comment]
Sorry!
